[package]
name = "pbd"
version = "0.0.4"
authors = ["dsietz <davidsietz@yahoo.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
keywords = ["data", "privacy", "sdk", "design", "development"]
categories = ["web-programming", "development-tools", "data-structures","config"]
description = "A software development kit for Privacy by Design (PbD)."
documentation = "https://docs.rs/pbd"
repository = "https://github.com/dsietz/pbd"
exclude = [
    "examples/*",
    "target/*",
	"tests/*",
	"benches/*",
]

[badges]
maintenance = {status = "actively-developed"}

[dependencies]
log = "0.4"
serde ="1.0"
serde_derive = "1.0"
serde_json = "1.0"
derive_more = "0.99"
json = "0.11"
actix-web = "1.0"
actix-service = "0.4"
futures = "0.3"