use serde_json::Value;

pub fn read_json_data_categories() -> Value {
    let data = r#"[
        {
          "fides_key": "system",
          "is_default": true,
          "name": "System Data",
          "organization_fides_key": "default_organization",
          "parent_key": null,
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Data unique to, and under control of the system."
        },
        {
          "fides_key": "system.authentication",
          "is_default": true,
          "name": "Authentication Data",
          "organization_fides_key": "default_organization",
          "parent_key": "system",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Data used to manage access to the system."
        },
        {
          "fides_key": "system.operations",
          "is_default": true,
          "name": "Operations Data",
          "organization_fides_key": "default_organization",
          "parent_key": "system",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Data used for system operations."
        },
        {
          "fides_key": "user",
          "is_default": true,
          "name": "User Data",
          "organization_fides_key": "default_organization",
          "parent_key": null,
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Data related to the user of the system, either provided directly or derived based on their usage."
        },
        {
          "fides_key": "user.account",
          "is_default": true,
          "name": "Account Information.",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Account creation or registration information."
        },
        {
          "fides_key": "user.authorization",
          "is_default": true,
          "name": "Authorization Information.",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Scope of permissions and access to a system."
        },
        {
          "fides_key": "user.behavior",
          "is_default": true,
          "name": "Observed Behavior",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Behavioral data about the subject."
        },
        {
          "fides_key": "user.biometric",
          "is_default": true,
          "name": "Biometric Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Encoded characteristics provided by a user."
        },
        {
          "fides_key": "user.childrens",
          "is_default": true,
          "name": "Children's Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Data relating to children."
        },
        {
          "fides_key": "user.contact",
          "is_default": true,
          "name": "Contact Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Contact data collected about a user."
        },
        {
          "fides_key": "user.content",
          "is_default": true,
          "name": "User Content",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Content related to, or created by the subject."
        },
        {
          "fides_key": "user.demographic",
          "is_default": true,
          "name": "Demographic Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Demographic data about a user."
        },
        {
          "fides_key": "user.location",
          "is_default": true,
          "name": "Location Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Records of the location of a user."
        },
        {
          "fides_key": "user.device",
          "is_default": true,
          "name": "Device Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Data related to a user's device, configuration and setting."
        },
        {
          "fides_key": "user.payment",
          "is_default": true,
          "name": "Payment Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Payment data related to user."
        },
        {
          "fides_key": "user.social",
          "is_default": true,
          "name": "Social Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Social activity and interaction data."
        },
        {
          "fides_key": "user.unique_id",
          "is_default": true,
          "name": "Unique ID",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Unique identifier for a user assigned through system use."
        },
        {
          "fides_key": "user.telemetry",
          "is_default": true,
          "name": "Telemetry Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "User identifiable measurement data from system sensors and monitoring."
        },
        {
          "fides_key": "user.user_sensor",
          "is_default": true,
          "name": "User Sensor Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Measurement data about a user's environment through system use."
        },
        {
          "fides_key": "user.workplace",
          "is_default": true,
          "name": "Workplace",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Organization of employment."
        },
        {
          "fides_key": "user.sensor",
          "is_default": true,
          "name": "Sensor Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Measurement data from sensors and monitoring systems."
        },
        {
          "fides_key": "user.financial",
          "is_default": true,
          "name": "Financial Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Payment data and financial history."
        },
        {
          "fides_key": "user.government_id",
          "is_default": true,
          "name": "Government ID",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "State provided identification data."
        },
        {
          "fides_key": "user.health_and_medical",
          "is_default": true,
          "name": "Health and Medical Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Health records or individual's personal medical information."
        },
        {
          "fides_key": "user.name",
          "is_default": true,
          "name": "Name",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "User's real name."
        },
        {
          "fides_key": "user.criminal_history",
          "is_default": true,
          "name": "Criminal History",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Criminal records or information about the data subject."
        },
        {
          "fides_key": "user.privacy_preferences",
          "is_default": true,
          "name": "Privacy Preferences",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Privacy preferences or settings set by the subject."
        },
        {
          "fides_key": "user.job_title",
          "is_default": true,
          "name": "Job Title",
          "organization_fides_key": "default_organization",
          "parent_key": "user",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Professional data."
        },
        {
          "fides_key": "user.account.settings",
          "is_default": true,
          "name": "Account Settings",
          "organization_fides_key": "default_organization",
          "parent_key": "user.account",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Account preferences and settings."
        },
        {
          "fides_key": "user.account.username",
          "is_default": true,
          "name": "Account Username",
          "organization_fides_key": "default_organization",
          "parent_key": "user.account",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Username associated with account."
        },
        {
          "fides_key": "user.authorization.credentials",
          "is_default": true,
          "name": "Account password.",
          "organization_fides_key": "default_organization",
          "parent_key": "user.authorization",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Authentication credentials to a system."
        },
        {
          "fides_key": "user.authorization.biometric",
          "is_default": true,
          "name": "Biometric Credentials",
          "organization_fides_key": "default_organization",
          "parent_key": "user.authorization",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Credentials for system authentication."
        },
        {
          "fides_key": "user.authorization.password",
          "is_default": true,
          "name": "Password",
          "organization_fides_key": "default_organization",
          "parent_key": "user.authorization",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Password for system authentication."
        },
        {
          "fides_key": "user.behavior.browsing_history",
          "is_default": true,
          "name": "Browsing History",
          "organization_fides_key": "default_organization",
          "parent_key": "user.behavior",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Content browsing history of a user."
        },
        {
          "fides_key": "user.behavior.media_consumption",
          "is_default": true,
          "name": "Media Consumption",
          "organization_fides_key": "default_organization",
          "parent_key": "user.behavior",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Content consumption history of the subject."
        },
        {
          "fides_key": "user.behavior.purchase_history",
          "is_default": true,
          "name": "Purchase History",
          "organization_fides_key": "default_organization",
          "parent_key": "user.behavior",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Purchase history of the subject."
        },
        {
          "fides_key": "user.behavior.search_history",
          "is_default": true,
          "name": "Search History",
          "organization_fides_key": "default_organization",
          "parent_key": "user.behavior",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Search history of the subject."
        },
        {
          "fides_key": "user.biometric.fingerprint",
          "is_default": true,
          "name": "Fingerprint",
          "organization_fides_key": "default_organization",
          "parent_key": "user.biometric",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Fingerprint encoded data about a subject."
        },
        {
          "fides_key": "user.biometric.retinal",
          "is_default": true,
          "name": "Retina Scan",
          "organization_fides_key": "default_organization",
          "parent_key": "user.biometric",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Retinal data about a subject."
        },
        {
          "fides_key": "user.biometric.voice",
          "is_default": true,
          "name": "Voice Recording",
          "organization_fides_key": "default_organization",
          "parent_key": "user.biometric",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Voice encoded data about a subject."
        },
        {
          "fides_key": "user.biometric.health",
          "is_default": true,
          "name": "Biometric Health Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user.biometric",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Encoded characteristic collected about a user."
        },
        {
          "fides_key": "user.contact.address",
          "is_default": true,
          "name": "User Contact Address",
          "organization_fides_key": "default_organization",
          "parent_key": "user.contact",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Contact address data collected about a user."
        },
        {
          "fides_key": "user.contact.email",
          "is_default": true,
          "name": "User Contact Email",
          "organization_fides_key": "default_organization",
          "parent_key": "user.contact",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "User's contact email address."
        },
        {
          "fides_key": "user.contact.phone_number",
          "is_default": true,
          "name": "User Contact Phone Number",
          "organization_fides_key": "default_organization",
          "parent_key": "user.contact",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "User's phone number."
        },
        {
          "fides_key": "user.contact.url",
          "is_default": true,
          "name": "User Website",
          "organization_fides_key": "default_organization",
          "parent_key": "user.contact",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Subject's websites or links to social and personal profiles."
        },
        {
          "fides_key": "user.contact.fax_number",
          "is_default": true,
          "name": "Fax Number",
          "organization_fides_key": "default_organization",
          "parent_key": "user.contact",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Data Subject's fax number."
        },
        {
          "fides_key": "user.contact.organization",
          "is_default": true,
          "name": "Organization",
          "organization_fides_key": "default_organization",
          "parent_key": "user.contact",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Data Subject's Organization."
        },
        {
          "fides_key": "user.contact.address.city",
          "is_default": true,
          "name": "User Contact City",
          "organization_fides_key": "default_organization",
          "parent_key": "user.contact.address",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "User's city level address data."
        },
        {
          "fides_key": "user.contact.address.country",
          "is_default": true,
          "name": "User Contact Country",
          "organization_fides_key": "default_organization",
          "parent_key": "user.contact.address",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "User's country level address data."
        },
        {
          "fides_key": "user.contact.address.postal_code",
          "is_default": true,
          "name": "User Contact Postal Code",
          "organization_fides_key": "default_organization",
          "parent_key": "user.contact.address",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "User's postal code."
        },
        {
          "fides_key": "user.contact.address.state",
          "is_default": true,
          "name": "User Contact State",
          "organization_fides_key": "default_organization",
          "parent_key": "user.contact.address",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "User's state level address data."
        },
        {
          "fides_key": "user.contact.address.street",
          "is_default": true,
          "name": "User Contact Street",
          "organization_fides_key": "default_organization",
          "parent_key": "user.contact.address",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "User's street level address data."
        },
        {
          "fides_key": "user.content.private",
          "is_default": true,
          "name": "Private Content",
          "organization_fides_key": "default_organization",
          "parent_key": "user.content",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Private content related to, or created by the subject, not publicly available."
        },
        {
          "fides_key": "user.content.public",
          "is_default": true,
          "name": "Public Content",
          "organization_fides_key": "default_organization",
          "parent_key": "user.content",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Publicly shared Content related to, or created by the subject."
        },
        {
          "fides_key": "user.content.self_image",
          "is_default": true,
          "name": "User Image",
          "organization_fides_key": "default_organization",
          "parent_key": "user.content",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Photograph or image in which subject is whole or partially recognized."
        },
        {
          "fides_key": "user.demographic.age_range",
          "is_default": true,
          "name": "Age Range",
          "organization_fides_key": "default_organization",
          "parent_key": "user.demographic",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Non specific age or age-range of data subject."
        },
        {
          "fides_key": "user.demographic.date_of_birth",
          "is_default": true,
          "name": "Birth Date",
          "organization_fides_key": "default_organization",
          "parent_key": "user.demographic",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Date of birth of data subject."
        },
        {
          "fides_key": "user.demographic.gender",
          "is_default": true,
          "name": "Gender",
          "organization_fides_key": "default_organization",
          "parent_key": "user.demographic",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Gender of data subject."
        },
        {
          "fides_key": "user.demographic.language",
          "is_default": true,
          "name": "Language",
          "organization_fides_key": "default_organization",
          "parent_key": "user.demographic",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Spoken or written language of subject."
        },
        {
          "fides_key": "user.demographic.marital_status",
          "is_default": true,
          "name": "Marital Status",
          "organization_fides_key": "default_organization",
          "parent_key": "user.demographic",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Marital status of data subject."
        },
        {
          "fides_key": "user.demographic.political_opinion",
          "is_default": true,
          "name": "Political Opinion",
          "organization_fides_key": "default_organization",
          "parent_key": "user.demographic",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Political opinion or belief of data subject."
        },
        {
          "fides_key": "user.demographic.profile",
          "is_default": true,
          "name": "User Profile Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user.demographic",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Profile or preference information about the data subject."
        },
        {
          "fides_key": "user.demographic.race_ethnicity",
          "is_default": true,
          "name": "Race",
          "organization_fides_key": "default_organization",
          "parent_key": "user.demographic",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Race or ethnicity of data subject."
        },
        {
          "fides_key": "user.demographic.religious_belief",
          "is_default": true,
          "name": "Religion",
          "organization_fides_key": "default_organization",
          "parent_key": "user.demographic",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Religion or religious beliefs of the data subject."
        },
        {
          "fides_key": "user.demographic.sexual_orientation",
          "is_default": true,
          "name": "Sexual Orientation",
          "organization_fides_key": "default_organization",
          "parent_key": "user.demographic",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Sexual orientation of data subject."
        },
        {
          "fides_key": "user.device.cookie",
          "is_default": true,
          "name": "Device Cookie",
          "organization_fides_key": "default_organization",
          "parent_key": "user.device",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Data related to a subject, stored within a cookie."
        },
        {
          "fides_key": "user.device.cookie_id",
          "is_default": true,
          "name": "Cookie ID",
          "organization_fides_key": "default_organization",
          "parent_key": "user.device",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Cookie unique identification number."
        },
        {
          "fides_key": "user.device.device_id",
          "is_default": true,
          "name": "Device ID",
          "organization_fides_key": "default_organization",
          "parent_key": "user.device",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Device unique identification number."
        },
        {
          "fides_key": "user.device.ip_address",
          "is_default": true,
          "name": "IP Address",
          "organization_fides_key": "default_organization",
          "parent_key": "user.device",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Unique identifier related to device connection."
        },
        {
          "fides_key": "user.financial.bank_account",
          "is_default": true,
          "name": "Bank Account Information",
          "organization_fides_key": "default_organization",
          "parent_key": "user.financial",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Bank account information belonging to the subject."
        },
        {
          "fides_key": "user.financial.credit_card",
          "is_default": true,
          "name": "Credit Card Information",
          "organization_fides_key": "default_organization",
          "parent_key": "user.financial",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Credit card information belonging to the subject."
        },
        {
          "fides_key": "user.government_id.birth_certificate",
          "is_default": true,
          "name": "Birth Certificate",
          "organization_fides_key": "default_organization",
          "parent_key": "user.government_id",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "State issued certificate of birth."
        },
        {
          "fides_key": "user.government_id.drivers_license_number",
          "is_default": true,
          "name": "Driver's License Number",
          "organization_fides_key": "default_organization",
          "parent_key": "user.government_id",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "State issued driving identification number."
        },
        {
          "fides_key": "user.government_id.immigration",
          "is_default": true,
          "name": "Immigration ID",
          "organization_fides_key": "default_organization",
          "parent_key": "user.government_id",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "State issued immigration or residency data."
        },
        {
          "fides_key": "user.government_id.national_identification_number",
          "is_default": true,
          "name": "National Identification Number",
          "organization_fides_key": "default_organization",
          "parent_key": "user.government_id",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "State issued personal identification number."
        },
        {
          "fides_key": "user.government_id.passport_number",
          "is_default": true,
          "name": "Passport Number",
          "organization_fides_key": "default_organization",
          "parent_key": "user.government_id",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "State issued passport data."
        },
        {
          "fides_key": "user.government_id.vehicle_registration",
          "is_default": true,
          "name": "Vehicle Registration",
          "organization_fides_key": "default_organization",
          "parent_key": "user.government_id",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "State issued license plate or vehicle registration data."
        },
        {
          "fides_key": "user.health_and_medical.genetic",
          "is_default": true,
          "name": "User's Genetic Data",
          "organization_fides_key": "default_organization",
          "parent_key": "user.health_and_medical",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Data about the genetic makeup provided by the subject."
        },
        {
          "fides_key": "user.health_and_medical.insurance_beneficiary_id",
          "is_default": true,
          "name": "Medical Insurance ID",
          "organization_fides_key": "default_organization",
          "parent_key": "user.health_and_medical",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Health insurance beneficiary number of the subject."
        },
        {
          "fides_key": "user.health_and_medical.record_id",
          "is_default": true,
          "name": "Medical Record ID",
          "organization_fides_key": "default_organization",
          "parent_key": "user.health_and_medical",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Medical record identifiers belonging to a subject."
        },
        {
          "fides_key": "user.location.imprecise",
          "is_default": true,
          "name": "Imprecise Subject Location",
          "organization_fides_key": "default_organization",
          "parent_key": "user.location",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Imprecise location derived from sensors (more than 500M)."
        },
        {
          "fides_key": "user.location.precise",
          "is_default": true,
          "name": "Precise Subject Location",
          "organization_fides_key": "default_organization",
          "parent_key": "user.location",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Precise location derived from sensors (less than 500M)."
        },
        {
          "fides_key": "user.name.first",
          "is_default": true,
          "name": "First Name",
          "organization_fides_key": "default_organization",
          "parent_key": "user.name",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Subject's first name."
        },
        {
          "fides_key": "user.name.last",
          "is_default": true,
          "name": "Last Name",
          "organization_fides_key": "default_organization",
          "parent_key": "user.name",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "Subject's last, or family, name."
        },
        {
          "fides_key": "user.unique_id.pseudonymous",
          "is_default": true,
          "name": "Pseudonymous User ID",
          "organization_fides_key": "default_organization",
          "parent_key": "user.unique_id",
          "replaced_by": null,
          "tags": null,
          "version_added": "2.0.0",
          "version_deprecated": null,
          "description": "A pseudonymous, or probabilistic identifier generated from other subject or device data belonging to the subject."
        }          
    ]"#;
    let v: Value = serde_json::from_str(data).unwrap();
    v
}