use serde_json::Value;

pub fn read_json_data_uses() -> Value {
    let data = r#"[
      {
        "fides_key": "analytics",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Analytics",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Provides analytics for activities such as system and advertising performance reporting, insights and fraud detection."
      },
      {
        "fides_key": "analytics.reporting",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Analytics for Reporting",
        "organization_fides_key": "default_organization",
        "parent_key": "analytics",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Provides analytics for general reporting such as system and advertising performance."
      },
      {
        "fides_key": "analytics.reporting.ad_performance",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Analytics for Advertising Performance",
        "organization_fides_key": "default_organization",
        "parent_key": "analytics.reporting",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Provides analytics for reporting of advertising performance."
      },
      {
        "fides_key": "analytics.reporting.content_performance",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Analytics for Content Performance",
        "organization_fides_key": "default_organization",
        "parent_key": "analytics.reporting",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Analytics for reporting on content performance."
      },
      {
        "fides_key": "analytics.reporting.campaign_insights",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Analytics for Insights",
        "organization_fides_key": "default_organization",
        "parent_key": "analytics.reporting",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Provides analytics for reporting of campaign insights related to advertising and promotion activities."
      },
      {
        "fides_key": "analytics.reporting.system",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Analytics for System Activity",
        "organization_fides_key": "default_organization",
        "parent_key": "analytics.reporting",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Provides analytics for reporting on system activity."
      },
      {
        "fides_key": "analytics.reporting.system.performance",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Analytics for System Performance",
        "organization_fides_key": "default_organization",
        "parent_key": "analytics.reporting.system",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Provides analytics for reporting on system performance."
      },
      {
        "fides_key": "collect",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Collect",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Collects or stores data in order to use it for another purpose which has not yet been expressly defined."
      },
      {
        "fides_key": "employment",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Employment",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Processes data for the purpose of recruitment or employment and human resources (HR) related activities."
      },
      {
        "fides_key": "employment.recruitment",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Employment Recruitment",
        "organization_fides_key": "default_organization",
        "parent_key": "employment",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Processes data of prospective employees for the purpose of recruitment."
      },
      {
        "fides_key": "essential",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Operates the service or product, including legal obligations, support and basic system operations."
      },
      {
        "fides_key": "essential.fraud_detection",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential Fraud Detection",
        "organization_fides_key": "default_organization",
        "parent_key": "essential",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Detects possible fraud or misuse of the product, service, application or system."
      },
      {
        "fides_key": "essential.legal_obligation",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential Legal Obligation",
        "organization_fides_key": "default_organization",
        "parent_key": "essential",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Provides service to meet a legal or compliance obligation such as consent management."
      },
      {
        "fides_key": "essential.service",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential for Service",
        "organization_fides_key": "default_organization",
        "parent_key": "essential",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Provides the essential product, service, application or system, without which the product/service would not be possible."
      },
      {
        "fides_key": "essential.service.authentication",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential Service Authentication",
        "organization_fides_key": "default_organization",
        "parent_key": "essential.service",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Authenticate users to the product, service, application or system."
      },
      {
        "fides_key": "essential.service.notifications",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential Service Notifications",
        "organization_fides_key": "default_organization",
        "parent_key": "essential.service",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Sends notifications about the product, service, application or system."
      },
      {
        "fides_key": "essential.service.operations",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential for Operations",
        "organization_fides_key": "default_organization",
        "parent_key": "essential.service",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Essential to ensure the operation of the product, service, application or system."
      },
      {
        "fides_key": "essential.service.payment_processing",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential for Payment Processing",
        "organization_fides_key": "default_organization",
        "parent_key": "essential.service",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Essential to processes payments for the product, service, application or system."
      },
      {
        "fides_key": "essential.service.security",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential for Security",
        "organization_fides_key": "default_organization",
        "parent_key": "essential.service",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Essential to provide security for the product, service, application or system"
      },
      {
        "fides_key": "essential.service.upgrades",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential for Service Upgrades",
        "organization_fides_key": "default_organization",
        "parent_key": "essential.service",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Provides timely system upgrade information options."
      },
      {
        "fides_key": "essential.service.notifications.email",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential Email Service Notifications",
        "organization_fides_key": "default_organization",
        "parent_key": "essential.service.notifications",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Sends email notifications about the product, service, application or system."
      },
      {
        "fides_key": "essential.service.notifications.sms",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential SMS Service Notifications",
        "organization_fides_key": "default_organization",
        "parent_key": "essential.service.notifications",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Sends SMS notifications about the product, service, application or system."
      },
      {
        "fides_key": "essential.service.operations.support",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential for Operations Support",
        "organization_fides_key": "default_organization",
        "parent_key": "essential.service.operations",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Provides support for the product, service, application or system."
      },
      {
        "fides_key": "essential.service.operations.improve",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential for Support Improvement",
        "organization_fides_key": "default_organization",
        "parent_key": "essential.service.operations",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Essential to optimize and improve support for the product, service, application or system."
      },
      {
        "fides_key": "finance",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Finance",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Enables finance and accounting activities such as audits and tax reporting."
      },
      {
        "fides_key": "functional",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Functional",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Used for specific, necessary, and legitimate purposes"
      },
      {
        "fides_key": "functional.storage",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Local Data Storage",
        "organization_fides_key": "default_organization",
        "parent_key": "functional",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Stores or accesses information from the device as needed when using a product, service, application, or system"
      },
      {
        "fides_key": "functional.service",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Service",
        "organization_fides_key": "default_organization",
        "parent_key": "functional",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Functions relating to provided services, products, applications or systems."
      },
      {
        "fides_key": "functional.service.improve",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Improve Service",
        "organization_fides_key": "default_organization",
        "parent_key": "functional.service",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Improves the specific product, service, application or system."
      },
      {
        "fides_key": "marketing",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Marketing",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Enables marketing, promotion, advertising and sales activities for the product, service, application or system."
      },
      {
        "fides_key": "marketing.advertising",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Advertising, Marketing or Promotion",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Advertises or promotes the product, service, application or system and associated services."
      },
      {
        "fides_key": "marketing.communications",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Marketing Communications",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Uses combined channels to message and market to a customer, user or prospect."
      },
      {
        "fides_key": "marketing.advertising.first_party",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "First Party Advertising",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing.advertising",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Serves advertisements based on first party data collected or derived about the user."
      },
      {
        "fides_key": "marketing.advertising.frequency_capping",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Frequency Capping",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing.advertising",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Restricts the number of times a specific advertisement is shown to an individual."
      },
      {
        "fides_key": "marketing.advertising.negative_targeting",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Negative Targeting",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing.advertising",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Enforces rules used to ensure a certain audience or group is not targeted by advertising."
      },
      {
        "fides_key": "marketing.advertising.profiling",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Profiling for Advertising",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing.advertising",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Creates audience profiles for the purpose of targeted advertising"
      },
      {
        "fides_key": "marketing.advertising.serving",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Essential for Serving Ads",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing.advertising",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Essential to the delivery of advertising and content."
      },
      {
        "fides_key": "marketing.advertising.third_party",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Third Party Advertising",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing.advertising",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Serves advertisements based on data within the system or joined with data provided by 3rd parties."
      },
      {
        "fides_key": "marketing.advertising.first_party.contextual",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "First Party Contextual Advertising",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing.advertising.first_party",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Serves advertisements based on current content being viewed by the user of the system or service."
      },
      {
        "fides_key": "marketing.advertising.first_party.targeted",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "First Party Personalized Advertising",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing.advertising.first_party",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Targets advertisements based on data collected or derived about the user from use of the system."
      },
      {
        "fides_key": "marketing.advertising.third_party.targeted",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Third Party Targeted Advertising",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing.advertising.third_party",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Targets advertisements based on data within the system or joined with data provided by 3rd parties."
      },
      {
        "fides_key": "marketing.communications.email",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Marketing Email Communications",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing.communications",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Sends email marketing communications."
      },
      {
        "fides_key": "marketing.communications.sms",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Marketing SMS Communications",
        "organization_fides_key": "default_organization",
        "parent_key": "marketing.communications",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Sends SMS marketing communications."
      },
      {
        "fides_key": "operations",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Operations",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Supports business processes necessary to the organization's operation."
      },
      {
        "fides_key": "personalize",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Personalize",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Personalizes the product, service, application or system."
      },
      {
        "fides_key": "personalize.content",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Content Personalization",
        "organization_fides_key": "default_organization",
        "parent_key": "personalize",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Personalizes the content of the product, service, application or system."
      },
      {
        "fides_key": "personalize.profiling",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Personalized Profiling",
        "organization_fides_key": "default_organization",
        "parent_key": "personalize",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Creates profiles for the purpose of serving content."
      },
      {
        "fides_key": "personalize.system",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "System Personalization",
        "organization_fides_key": "default_organization",
        "parent_key": "personalize",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Personalizes the system."
      },
      {
        "fides_key": "sales",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Sales",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Supports sales activities such as communications and outreach."
      },
      {
        "fides_key": "third_party_sharing",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Third Party Sharing",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Transfers data to third parties outside of the system or service's scope."
      },
      {
        "fides_key": "third_party_sharing.legal_obligation",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Sharing for Legal Obligation",
        "organization_fides_key": "default_organization",
        "parent_key": "third_party_sharing",
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Shares data for legal obligations, including contracts, applicable laws or regulations."
      },
      {
        "fides_key": "train_ai_system",
        "is_default": true,
        "legal_basis": null,
        "legitimate_interest": null,
        "legitimate_interest_impact_assessment": null,
        "name": "Train AI System",
        "organization_fides_key": "default_organization",
        "parent_key": null,
        "recipients": null,
        "replaced_by": null,
        "special_category": null,
        "tags": null,
        "version_added": "2.0.0",
        "version_deprecated": null,
        "description": "Trains an AI system or data model for machine learning."
      }
    ]"#;
    let v: Value = serde_json::from_str(data).unwrap();
    v
}
